version: '2'

services:
  auth:
    image: hbpauth
    networks:
      - net
    ports:
      - "80:80"

  proxy:
    image: traefik
    command: --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    networks:
      - net
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  hub:
    image: servicehub
    labels:
      traefik.frontend.rule: "HostRegexp:localhost,{subdomain:[a-z]+}.localhost"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

networks:
  net:
    driver: bridge
